name: CI

on: 
  push:
    branches: [master, main]

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7

      - name: Install dependencies
        run:
          python -m pip install --upgrade pip
          pip install flake8
          pip install -r requirements.txt

      - name: Test with flake8
        run:
          python -m flake8